### ISSUE TITLE
iOS 12?

### ISSUE THREAD

**Issue by sirius247** [SparkDev97/libSparkAppList#1]
Hello,

can you possibly update this for iOS 12? Currently wont work. It allows blacklisted apps to pass through.

**Comment by SparkDev97** [comment]
It is fully working on iOS 12. See my tweaks such as TapticKeys, Myriad, Notchless.
If it is not working, it must be an issue with the implementation. I’d be happy to help you sort it out, best place to reach me is on my discord server.
