### ISSUE TITLE
Doesn't receive notification.

### ISSUE THREAD

**Issue by nicho1asdev** [SparkDev97/libSparkAppList#3]
I initialise the SparkAppListTableViewController with for instance "com.nicho1asdev.dyadic" and I register a notification for the name "com.nicho1asdev.dyadic.sparkapplistupdate" I don't receive any notifications when toggling an app.

**Comment by SparkDev97** [comment]
You need to register for a notification using NSNotificationCenter

[[NSNotificationCenter defaultCenter] addObserver:self
        selector:@selector(receiveNotification:) 
        name:@"com.nicho1asdev.dyadic.sparkapplistupdate"
        object:nil];

I just checked this and it is working.

You can do this yourself by adding that code to your prefs bundle, and posting back to your tweak in whatever process using an IPC method.
