### ISSUE TITLE
Snowboard Don’t Work 13.5

### ISSUE THREAD

**Issue by miguelr4720** [SparkDev97/libSparkAppList#4]
Snowboard Don’t Work Unc0ver Jailbrake 13.5

To Reproduce

Go to Snowboard on Cydia
Click on Snowboard and Install
Go to Home Screen to Move or Edit Apps
Safe Mode Occurs
Screenshots

Device (please complete the following information):

iOS Version: 13.5
iOS Device: iPhone 11 Pro Max
unc0ver Version: 3.0.5
Place an "x" between the brackets if true:

[X ] this is a bug others will be able to reproduce
[ X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
[X ] this issue is present after a rootfs restore
[X ] this issue is present on the latest version of unc0ver
Logs
If applicable, add logs or error messages here.

**Comment by SparkDev97** [comment]
This isn't a libsparkapplist isssue.

And make surer you have the build on my repo https://sparkdev.me

If you do, it must be conflicting with another tweak.
